# Generated by Django 4.0.6 on 2022-08-17 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mixs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name=django.db.models.deletion.PROTECT),
        ),
    ]
