# Generated by Django 4.0.6 on 2022-08-17 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.IntegerField(verbose_name='批号')),
            ],
            options={
                'verbose_name': '批号',
                'verbose_name_plural': '批号',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '操作员',
                'verbose_name_plural': '操作员',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mv', models.CharField(max_length=255, verbose_name='门尼')),
                ('mv_min', models.FloatField(verbose_name='门尼最小值')),
                ('mv_max', models.FloatField(verbose_name='门尼最大值')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mixs.customer')),
            ],
            options={
                'verbose_name': '品名清单',
                'verbose_name_plural': '品名清单',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField(verbose_name='回数')),
                ('mv', models.FloatField(verbose_name='门尼值')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mixs.item')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mixs.lot')),
            ],
            options={
                'verbose_name': '检查成绩表',
                'verbose_name_plural': '检查成绩表',
            },
        ),
    ]
