# Generated by Django 4.0.6 on 2022-07-31 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_category_flower_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='flower',
            name='tags',
            field=models.ManyToManyField(to='myapp.tag'),
        ),
    ]
