# Generated by Django 4.0.6 on 2022-08-13 04:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 13, 4, 45, 22, 700206, tzinfo=utc), verbose_name='Date published'),
        ),
    ]
