# Generated by Django 4.0.6 on 2022-08-13 09:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 13, 9, 58, 51, 686460, tzinfo=utc), verbose_name='Date published'),
        ),
    ]
