# Generated by Django 4.0.6 on 2022-08-21 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mixs_dup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail',
            options={'verbose_name': '详细信息', 'verbose_name_plural': '详细信息'},
        ),
        migrations.CreateModel(
            name='DetailChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_log', models.CharField(max_length=255, verbose_name='变更记录')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mixs_dup.detail')),
            ],
        ),
    ]
