# Generated by Django 4.1 on 2022-09-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixs_dup', '0003_detail_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='ship_status',
            field=models.IntegerField(choices=[(0, '未出货'), (1, '已出货')], default=0, verbose_name='出货状态'),
        ),
    ]
