# Generated by Django 4.1 on 2022-09-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixs_dup', '0005_remove_detail_ship_status_detail_shipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rotor',
            field=models.CharField(default='ML 1+4', max_length=255, verbose_name='转子'),
        ),
        migrations.AddField(
            model_name='item',
            name='temperature',
            field=models.IntegerField(blank=True, default=100, verbose_name='温度'),
        ),
    ]
